install:
	cp write_1d_bp.pbs write_1d_nc4.pbs write_1d_nc5.pbs /tmp/work/ge1/a/1d
	cp run_1d_bp.pbs run_1d_nc4.pbs run_1d_nc5.pbs /tmp/work/ge1/a/1d

	cp write_2d_bp.pbs write_2d_nc4.pbs write_2d_nc5.pbs /tmp/work/ge1/a/2d
	cp run_2d_bp.pbs run_2d_nc5.pbs /tmp/work/ge1/a/2d
	cp run_2d_nc4_7k.pbs run_2d_nc4_16k.pbs /tmp/work/ge1/a/2d
	cp run_2d_bp_7k_s[123456789].pbs /tmp/work/ge1/a/2d
	cp run_2d_bp_7k_s1[01].pbs /tmp/work/ge1/a/2d
	cp run_2d_bp_16k_s[123456789].pbs /tmp/work/ge1/a/2d
	cp run_2d_bp_16k_s1[012345678].pbs /tmp/work/ge1/a/2d
	cp run_2d_nc4_7k_s[12345].pbs /tmp/work/ge1/a/2d
	cp run_2d_nc4_16k_s[12345].pbs /tmp/work/ge1/a/2d

	cp write_3d_bp.pbs write_3d_nc4.pbs write_3d_nc5.pbs /tmp/work/ge1/a/3d
	cp write_3d_nc4_7k.pbs /tmp/work/ge1/a/3d
	cp write_3d_nc4_16k_sml.pbs write_3d_nc4_16k_xl.pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_7k.pbs run_3d_nc4_7k.pbs run_3d_nc5.pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_16k.pbs run_3d_nc4_16k.pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_7k_s[123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_7k_s1[0123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_7k_s2[012].pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_16k_s[123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_16k_s1[0123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_bp_16k_s2[0123456].pbs /tmp/work/ge1/a/3d
	cp run_3d_nc4_7k_s[123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_nc4_7k_s1[0123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_nc4_7k_s2[0123456789].pbs /tmp/work/ge1/a/3d
	cp run_3d_nc4_7k_s3[012].pbs /tmp/work/ge1/a/3d
