#!/bin/sh
#PBS -A CSC024adio
#PBS -N read_2d_nc4_7k_s2
#PBS -o /tmp/work/ge1/a/2d/read.2d.nc4.7k.s2.out
#PBS -e /tmp/work/ge1/a/2d/read.2d.nc4.7k.s2.err
#PBS -l walltime=02:00:00,size=516

write_prog=write_2d_nc4
read_prog=read_2d_nc4
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 0
export MPICH_MAX_SHORT_MSG_SIZE=64000

echo Run 2-D tests $write_prog $read_prog $flush_prog
date

####################### NC4 #####################
#################################################
# READ TESTS
#################################################

for p in 108 112 116 120 124 128 132 136 140 144 148 152 156 160 164 168 172 176 180 184 188 192 196 200 204 208
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 3 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 4 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 5 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 6 2d_112_64 112 64
echo flush
date

done
done

