#!/bin/sh
#PBS -A CSC024adio
#PBS -N read_2d_bp_7k_s1
#PBS -o /tmp/work/ge1/a/2d/read.2d.bp.7k.s1.out
#PBS -e /tmp/work/ge1/a/2d/read.2d.bp.7k.s1.err
#PBS -l walltime=02:00:00,size=516

write_prog=write_2d_bp
read_prog=read_2d_bp
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 0
export MPICH_MAX_SHORT_MSG_SIZE=32000

echo Run 2-D tests $write_prog $read_prog $flush_prog
date

####################### BP #####################
#################################################
# READ TESTS
#################################################

for p in 4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96 100 104 108 112 116 120 124 128 132 136 140 144 148 152 156 160 164 168 172 176 
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 3 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 4 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 5 2d_112_64 112 64
echo flush
date

aprun -n $p $read_prog 6 2d_112_64 112 64
echo flush
date

done
done

