#!/bin/sh
#PBS -A CSC024adio
#PBS -N read_3d_bp_16k_s13
#PBS -o /tmp/work/ge1/a/3d/read.3d.bp.16k.s13.out
#PBS -e /tmp/work/ge1/a/3d/read.3d.bp.16k.s13.err
#PBS -l walltime=02:00:00,size=516

write_prog=write_3d_bp
read_prog=read_3d_bp
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 0
export MPICH_MAX_SHORT_MSG_SIZE=64000

echo Run 3-D tests $write_prog $read_prog $flush_prog
date

#################################################
# READ TESTS
#################################################

for p in 236 240 244 248 252 
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

for per_proc_size in 32_32_32 64_64_64 128_128_128 256_256_256
do

aprun -n $p $read_prog 2 3d_32_32_16_${per_proc_size} 32 32 16
echo flush
date

aprun -n $p $read_prog 3 3d_32_32_16_${per_proc_size} 32 32 16
echo flush
date

aprun -n $p $read_prog 4 3d_32_32_16_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 5 3d_32_32_16_${per_proc_size} 32 32 16
echo flush
date

aprun -n $p $read_prog 6 3d_32_32_16_${per_proc_size} 128 128
echo flush
date

done
done
done

