#!/bin/sh
#PBS -A CSC024adio
#PBS -N write_1d_bp
#PBS -o /tmp/work/ge1/a/1d/write.1d.bp.out
#PBS -e /tmp/work/ge1/a/1d/write.1d.bp.err
#PBS -l walltime=00:15:00,size=16392

write_prog=write_1d_bp
read_prog=read_1d_bp
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 500
export MPICH_MAX_SHORT_MSG_SIZE=64000

echo Run 1-D create test files $write_prog $read_prog $flush_prog
date

####################### BP #####################
# 7168 procs
aprun -n 7168 $write_prog 1d_7168
date

# 16384 procs
aprun -n 16384 $write_prog 1d_16384
date
