#!/bin/sh
#PBS -A CSC024adio
#PBS -N write_3d_nc4_7k
#PBS -o /tmp/work/ge1/a/3d/write.3d.nc4.7k.out
#PBS -e /tmp/work/ge1/a/3d/write.3d.nc4.7k.err
#PBS -l walltime=11:00:00,size=7176

write_prog=write_3d_nc4
read_prog=read_3d_nc4
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 200
export MPICH_UNEX_BUFFER_SIZE=90000000
export MPICH_MAX_SHORT_MSG_SIZE=30000
export MPICH_PTL_OTHER_EVENTS=4096

echo Run 3-D tests $write_prog $read_prog $flush_prog
date

####################### NC4 #####################
# 7168 procs
aprun -n 7168 $write_prog 3d_28_16_16_32_32_32 28 16 16 32 32 32
date
aprun -n 7168 $write_prog 3d_28_16_16_64_64_64 28 16 16 64 64 64
date
aprun -n 7168 $write_prog 3d_28_16_16_128_128_128 28 16 16 128 128 128
date
aprun -n 7168 $write_prog 3d_28_16_16_256_256_256 28 16 16 256 256 256
date
