#!/bin/sh
#PBS -A CSC024adio
#PBS -N read_1d_bp
#PBS -o /tmp/work/ge1/a/1d/run.stdout.1d.bp
#PBS -e /tmp/work/ge1/a/1d/run.stderr.1d.bp
#PBS -l walltime=04:00:00,size=8004

write_prog=write_1d_bp
read_prog=read_1d_bp
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 0
export MPICH_MAX_SHORT_MSG_SIZE=64000

echo Run 1-D tests $write_prog $read_prog $flush_prog
date

####################### BP #####################
# 1000 procs
aprun -n 1000 $write_prog 1d_1000
date

# 2000 procs
aprun -n 2000 $write_prog 1d_2000
date

# 4000 procs
aprun -n 4000 $write_prog 1d_4000
date

# 8000 procs
aprun -n 8000 $write_prog 1d_8000
date

#################################################
# READ TESTS
#################################################

date
# 1000 reader procs (1000 writer procs)
for i in 1 2 3 4 5
do
for filename in 1d_1000
do
aprun -n 1000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

# 500 reader procs (1000 writers)
for i in 1 2 3 4 5
do
for filename in 1d_1000
do
aprun -n 500 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 500 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 500 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 500 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 500 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

################################################

# 2000 reader procs (2000 writer procs)
for i in 1 2 3 4 5
do
for filename in 1d_2000
do
aprun -n 2000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

# 1000 reader procs (2000 writers)
for i in 1 2 3 4 5
do
for filename in 1d_2000
do
aprun -n 1000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 1000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

################################################

# 4000 reader procs (4000 writer procs)
for i in 1 2 3 4 5
do
for filename in 1d_4000
do
aprun -n 4000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

# 2000 reader procs (4000 writers)
for i in 1 2 3 4 5
do
for filename in 1d_4000
do
aprun -n 2000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 2000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

################################################

# 8000 reader procs (8000 writer procs)
for i in 1 2 3 4 5
do
for filename in 1d_8000
do
aprun -n 8000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 8000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 8000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 8000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 8000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done

# 4000 reader procs (8000 writers)
for i in 1 2 3 4 5
do
for filename in 1d_8000
do
aprun -n 4000 $read_prog 2 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 3 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 4 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 5 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date

aprun -n 4000 $read_prog 6 $filename
date
aprun -n 1000 $flush_prog flush 10 10 10 256 256 256
date
done
done
