#!/bin/sh

write_prog=write_3d_bp
read_prog=read_3d_bp
flush_prog=write_3d_bp

echo Run 3-D tests $write_prog $read_prog $flush_prog
date

#################################################
# READ TESTS
#################################################

for p in 512 1024 1536 2048 2560 3072 3584 4096
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 3 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 4 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 5 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 6 2d_112_64_${per_proc_size} 112 64
echo flush
date

done
done

for p in 512 1024 1536 2048 2560 3072 3584 4096
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 3 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 4 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 5 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 6 2d_128_128_${per_proc_size} 128 128
echo flush
date

done
done

