install:
	cp run_1d_bp.pbs run_1d_nc4.pbs run_1d_nc5.pbs /tmp/work/ge1/a/1d
	cp write_1d_bp.pbs write_1d_nc4.pbs write_1d_nc5.pbs /tmp/work/ge1/a/1d
	cp run_2d_bp.pbs run_2d_nc4.pbs run_2d_nc5.pbs /tmp/work/ge1/a/2d
	cp write_2d_bp.pbs write_2d_nc4.pbs write_2d_nc5.pbs /tmp/work/ge1/a/2d
	cp run_3d_bp.pbs run_3d_nc4_7k.pbs run_3d_nc5.pbs /tmp/work/ge1/a/3d
	cp run_3d_nc4_16k.pbs /tmp/work/ge1/a/3d
	cp write_3d_bp.pbs write_3d_nc4.pbs write_3d_nc5.pbs /tmp/work/ge1/a/3d
	cp write_3d_nc4_7k.pbs /tmp/work/ge1/a/3d
	cp write_3d_nc4_16k_sml.pbs write_3d_nc4_16k_xl.pbs /tmp/work/ge1/a/3d
