#!/bin/sh
#PBS -A CSC024adio
#PBS -N read_2d_bp
#PBS -o /tmp/work/ge1/a/2d/read.2d.bp.out
#PBS -e /tmp/work/ge1/a/2d/read.2d.bp.err
#PBS -l walltime=01:00:00,size=16392

write_prog=write_2d_bp
read_prog=read_2d_bp
flush_prog=write_3d_bp

cd $PBS_O_WORKDIR
lfs setstripe . -c 160 -i 0
export MPICH_MAX_SHORT_MSG_SIZE=32000

echo Run 2-D tests $write_prog $read_prog $flush_prog
date

####################### BP #####################
#################################################
# READ TESTS
#################################################

for p in 512 1024 1536 2048 2560 3072 3584 4096
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 3 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 4 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 5 2d_112_64_${per_proc_size} 112 64
echo flush
date

aprun -n $p $read_prog 6 2d_112_64_${per_proc_size} 112 64
echo flush
date

done
done

for p in 512 1024 1536 2048 2560 3072 3584 4096
do

#hp=`expr $p / 2`

for i in 1 2 3 4 5
do

aprun -n $p $read_prog 2 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 3 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 4 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 5 2d_128_128_${per_proc_size} 128 128
echo flush
date

aprun -n $p $read_prog 6 2d_128_128_${per_proc_size} 128 128
echo flush
date

done
done

